/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.biblioteca.vista.paneles;

/**
 *
 * @author ibarr
 */
public class LectoresPanel extends javax.swing.JPanel {

    /**
     * Creates new form LectoresPanel
     */
    public LectoresPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleRegistroLectoresjLabel = new javax.swing.JLabel();
        TablajScrollPane = new javax.swing.JScrollPane();
        TablaRLjTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleRegistroLectoresjLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TitleRegistroLectoresjLabel.setForeground(new java.awt.Color(29, 114, 129));
        TitleRegistroLectoresjLabel.setText("REGISTRO DE LECTORES");
        add(TitleRegistroLectoresjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        TablajScrollPane.setPreferredSize(new java.awt.Dimension(640, 420));

        TablaRLjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cèdula", "Barrio", "Hora de llegada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablajScrollPane.setViewportView(TablaRLjTable);

        add(TablajScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 350));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaRLjTable;
    private javax.swing.JScrollPane TablajScrollPane;
    private javax.swing.JLabel TitleRegistroLectoresjLabel;
    // End of variables declaration//GEN-END:variables
}
