/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.biblioteca.vista.paneles;

/**
 *
 * @author ibarr
 */
public class LibrosPanel extends javax.swing.JPanel {

    /**
     * Creates new form LibrosPanel
     */
    public LibrosPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGjPanel = new javax.swing.JPanel();
        TitleRegistroLibrojLabel = new javax.swing.JLabel();
        TablaScrollPane1 = new javax.swing.JScrollPane();
        TablaRegistroLibrosjTable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BGjPanel.setBackground(new java.awt.Color(255, 255, 255));
        BGjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleRegistroLibrojLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TitleRegistroLibrojLabel.setForeground(new java.awt.Color(29, 114, 129));
        TitleRegistroLibrojLabel.setText("REGISTRO DE LIBROS");
        BGjPanel.add(TitleRegistroLibrojLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        TablaRegistroLibrosjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Titulo", "Genero", "Autor", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaScrollPane1.setViewportView(TablaRegistroLibrosjTable);

        BGjPanel.add(TablaScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 640, 350));

        add(BGjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 420));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BGjPanel;
    private javax.swing.JTable TablaRegistroLibrosjTable;
    private javax.swing.JScrollPane TablaScrollPane1;
    private javax.swing.JLabel TitleRegistroLibrojLabel;
    // End of variables declaration//GEN-END:variables
}
