/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.biblioteca.vista.ventanas.home;

/**
 *
 * @author ibarr
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgjPanel = new javax.swing.JPanel();
        BGmenujPanel = new javax.swing.JPanel();
        TextInicioMenujLabel = new javax.swing.JLabel();
        TextLectoresMenujLabel1 = new javax.swing.JLabel();
        TextLibrosMenujLabel1 = new javax.swing.JLabel();
        TextConfiguracionMenujLabel1 = new javax.swing.JLabel();
        TextAcercaDeMenujLabel = new javax.swing.JLabel();
        BGINICIOjLabel = new javax.swing.JLabel();
        BGLectoresjLabel = new javax.swing.JLabel();
        BGLibrosjLabel = new javax.swing.JLabel();
        BGConfiguracionjLabel = new javax.swing.JLabel();
        BGAboutjLabel = new javax.swing.JLabel();
        BGPANELjPanel = new javax.swing.JPanel();
        BG_IMAGEN_BIBLIOTECAjLabel = new javax.swing.JLabel();
        TextConfiguracionjLabel = new javax.swing.JLabel();
        TextLibrosjLabel = new javax.swing.JLabel();
        TextLectoresjLabel = new javax.swing.JLabel();
        BGTextLectoresjLabel = new javax.swing.JLabel();
        BGTextLibrosjLabel = new javax.swing.JLabel();
        BGTextConfiguracionjLabel = new javax.swing.JLabel();
        BGToolBarjPanel = new javax.swing.JPanel();
        BTN_BURGERjLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BGIconNotificaionjLabel = new javax.swing.JLabel();
        BGIconUserjLabel = new javax.swing.JLabel();
        BGBarraBusquedajLabel = new javax.swing.JLabel();
        TextTitleBibliotecajLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BGmenujPanel.setBackground(new java.awt.Color(28, 142, 158));
        BGmenujPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextInicioMenujLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TextInicioMenujLabel.setForeground(new java.awt.Color(255, 255, 255));
        TextInicioMenujLabel.setText("INICIO");
        BGmenujPanel.add(TextInicioMenujLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 70, 40));

        TextLectoresMenujLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TextLectoresMenujLabel1.setForeground(new java.awt.Color(255, 255, 255));
        TextLectoresMenujLabel1.setText("LECTORES");
        BGmenujPanel.add(TextLectoresMenujLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 70, 30));

        TextLibrosMenujLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TextLibrosMenujLabel1.setForeground(new java.awt.Color(255, 255, 255));
        TextLibrosMenujLabel1.setText("LIBROS");
        BGmenujPanel.add(TextLibrosMenujLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 70, 30));

        TextConfiguracionMenujLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        TextConfiguracionMenujLabel1.setForeground(new java.awt.Color(255, 255, 255));
        TextConfiguracionMenujLabel1.setText("CONFIGURACION");
        BGmenujPanel.add(TextConfiguracionMenujLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 120, 40));

        TextAcercaDeMenujLabel.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        TextAcercaDeMenujLabel.setForeground(new java.awt.Color(255, 255, 255));
        TextAcercaDeMenujLabel.setText("ACERCA DE");
        BGmenujPanel.add(TextAcercaDeMenujLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 80, 40));

        BGINICIOjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        BGmenujPanel.add(BGINICIOjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 38, -1, -1));

        BGLectoresjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        BGmenujPanel.add(BGLectoresjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 84, -1, -1));

        BGLibrosjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        BGmenujPanel.add(BGLibrosjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 177, -1, -1));

        BGConfiguracionjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        BGmenujPanel.add(BGConfiguracionjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 131, -1, -1));

        BGAboutjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        BGmenujPanel.add(BGAboutjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 217, -1, -1));

        bgjPanel.add(BGmenujPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 258, 420));

        BGPANELjPanel.setBackground(new java.awt.Color(255, 255, 255));
        BGPANELjPanel.setPreferredSize(new java.awt.Dimension(640, 420));
        BGPANELjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BG_IMAGEN_BIBLIOTECAjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imagenBiblioteca.png"))); // NOI18N
        BGPANELjPanel.add(BG_IMAGEN_BIBLIOTECAjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        TextConfiguracionjLabel.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        TextConfiguracionjLabel.setForeground(new java.awt.Color(29, 114, 129));
        TextConfiguracionjLabel.setText("CONFIGURACIÒN");
        BGPANELjPanel.add(TextConfiguracionjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, 20));

        TextLibrosjLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TextLibrosjLabel.setForeground(new java.awt.Color(29, 114, 129));
        TextLibrosjLabel.setText("LIBROS");
        BGPANELjPanel.add(TextLibrosjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        TextLectoresjLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TextLectoresjLabel.setForeground(new java.awt.Color(29, 114, 129));
        TextLectoresjLabel.setText("LECTORES");
        BGPANELjPanel.add(TextLectoresjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        BGTextLectoresjLabel.setForeground(new java.awt.Color(29, 114, 129));
        BGTextLectoresjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadro.png"))); // NOI18N
        BGPANELjPanel.add(BGTextLectoresjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 140, 40));

        BGTextLibrosjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadro.png"))); // NOI18N
        BGPANELjPanel.add(BGTextLibrosjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 140, 40));

        BGTextConfiguracionjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadro.png"))); // NOI18N
        BGPANELjPanel.add(BGTextConfiguracionjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 160, 40));

        bgjPanel.add(BGPANELjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 640, 420));

        BGToolBarjPanel.setBackground(new java.awt.Color(255, 255, 255));

        BTN_BURGERjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/moneda.png"))); // NOI18N

        BGIconNotificaionjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/notifi.png"))); // NOI18N

        BGIconUserjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N

        BGBarraBusquedajLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buquedaBarra.png"))); // NOI18N

        TextTitleBibliotecajLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TextTitleBibliotecajLabel.setForeground(new java.awt.Color(29, 114, 129));
        TextTitleBibliotecajLabel.setText("BIBLIOTECA");

        javax.swing.GroupLayout BGToolBarjPanelLayout = new javax.swing.GroupLayout(BGToolBarjPanel);
        BGToolBarjPanel.setLayout(BGToolBarjPanelLayout);
        BGToolBarjPanelLayout.setHorizontalGroup(
            BGToolBarjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGToolBarjPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(BTN_BURGERjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextTitleBibliotecajLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(BGBarraBusquedajLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(BGIconNotificaionjLabel)
                .addGap(18, 18, 18)
                .addComponent(BGIconUserjLabel)
                .addGap(39, 39, 39))
        );
        BGToolBarjPanelLayout.setVerticalGroup(
            BGToolBarjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BTN_BURGERjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BGToolBarjPanelLayout.createSequentialGroup()
                .addGroup(BGToolBarjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BGToolBarjPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BGBarraBusquedajLabel))
                    .addGroup(BGToolBarjPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(BGToolBarjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BGIconNotificaionjLabel)
                            .addComponent(jLabel10)
                            .addComponent(BGIconUserjLabel)))
                    .addGroup(BGToolBarjPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(TextTitleBibliotecajLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bgjPanel.add(BGToolBarjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 80));

        getContentPane().add(bgjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGAboutjLabel;
    private javax.swing.JLabel BGBarraBusquedajLabel;
    private javax.swing.JLabel BGConfiguracionjLabel;
    private javax.swing.JLabel BGINICIOjLabel;
    private javax.swing.JLabel BGIconNotificaionjLabel;
    private javax.swing.JLabel BGIconUserjLabel;
    private javax.swing.JLabel BGLectoresjLabel;
    private javax.swing.JLabel BGLibrosjLabel;
    private javax.swing.JPanel BGPANELjPanel;
    private javax.swing.JLabel BGTextConfiguracionjLabel;
    private javax.swing.JLabel BGTextLectoresjLabel;
    private javax.swing.JLabel BGTextLibrosjLabel;
    private javax.swing.JPanel BGToolBarjPanel;
    private javax.swing.JLabel BG_IMAGEN_BIBLIOTECAjLabel;
    private javax.swing.JPanel BGmenujPanel;
    private javax.swing.JLabel BTN_BURGERjLabel;
    private javax.swing.JLabel TextAcercaDeMenujLabel;
    private javax.swing.JLabel TextConfiguracionMenujLabel1;
    private javax.swing.JLabel TextConfiguracionjLabel;
    private javax.swing.JLabel TextInicioMenujLabel;
    private javax.swing.JLabel TextLectoresMenujLabel1;
    private javax.swing.JLabel TextLectoresjLabel;
    private javax.swing.JLabel TextLibrosMenujLabel1;
    private javax.swing.JLabel TextLibrosjLabel;
    private javax.swing.JLabel TextTitleBibliotecajLabel;
    private javax.swing.JPanel bgjPanel;
    private javax.swing.JLabel jLabel10;
    // End of variables declaration//GEN-END:variables
}
